In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./data/generated/gold_kpi_employee_status.csv")

In [4]:
df.head()

,employee_id,full_name,business_unit,is_bonus_eligible,bonus_amount,bonus_reason,is_wellbeing_eligible,wellbeing_days_awarded,wellbeing_reason,activity_count_12m,transport_mode,distance_km_to_office
0,12497,Gabriel Fontaine,R&D,f,1391.0,transport_non_sportif,t,5,eligible,30,velo/trottinette/autres,4.29
1,13064,Henriette Thibault,R&D,f,3749.5,transport_non_sportif,t,5,eligible,46,vehicule thermique/electrique,19.10
2,13780,Sylvain Renard,Finance,f,3010.0,transport_non_sportif,t,5,eligible,62,velo/trottinette/autres,12.45
3,15493,Alice Devaux,Support,f,3686.0,transport_non_sportif,t,5,eligible,16,vehicule thermique/electrique,2.59
4,16872,Francoise Toussaint,Finance,f,1528.0,transport_non_sportif,t,5,eligible,30,velo/trottinette/autres,4.96

In [7]:
df2 = pd.read_csv("./data/generated/gold_slack_messages.csv")
df2.head()

,message_id,activity_id,employee_id,channel_name,message_text,generated_at,status
0,a142a5cc-6265-4c53-9882-2f4354d9f693,18ccf387-1b4c-431b-a05c-195295007d57,12497,#sport-avantages,:runner: Activite walk enregistree pour le sal...,2026-04-25 08:13:34.597279+00,generated
1,cbe2313f-90e3-420e-9a96-1e633f5e9543,f0dc8faf-522f-4eea-aae1-56b76f116689,12497,#sport-avantages,:runner: Activite swim enregistree pour le sal...,2026-04-25 08:13:34.618579+00,generated
2,a09d101b-5d49-4c03-8155-d6926e676fef,4706a903-5fdb-46f5-96c3-67d5639ae7cb,12497,#sport-avantages,:runner: Activite run enregistree pour le sala...,2026-04-25 08:13:34.640113+00,generated
3,86f66bc3-72e9-4477-bc05-42f467774bc5,3cb94a61-7cf3-48d5-bbb5-3f363f3f1a40,12497,#sport-avantages,:runner: Activite swim enregistree pour le sal...,2026-04-25 08:13:34.661894+00,generated
4,4d572709-b3fd-4b80-a502-7ab0cae5ba73,bbdfda51-72cf-443f-86fb-f57ca217e9d1,12497,#sport-avantages,:runner: Activite hike enregistree pour le sal...,2026-04-25 08:13:34.686063+00,generated

In [8]:
df = pd.read_csv("./data/generated/gold_kpi_finance.csv")
df.head()

,reference_year,eligible_bonus_employees,eligible_wellbeing_employees,total_bonus_cost,avg_bonus_amount,activity_count_total
0,2026,12,161,32122.5,2676.88,7882

In [7]:
df['is_wellbeing_eligible'].value_counts()

is_wellbeing_eligible
t    161
Name: count, dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   employee_id             161 non-null    int64
 1   full_name               161 non-null    object
 2   business_unit           161 non-null    object
 3   is_bonus_eligible       161 non-null    object
 4   bonus_amount            161 non-null    float64
 5   bonus_reason            161 non-null    object
 6   is_wellbeing_eligible   161 non-null    object
 7   wellbeing_days_awarded  161 non-null    int64
 8   wellbeing_reason        161 non-null    object
 9   activity_count_12m      161 non-null    int64
 10  transport_mode          161 non-null    object
 11  distance_km_to_office   161 non-null    float64
dtypes: float64(2), int64(3), object(7)
memory usage: 15.2+ KB

In [21]:
dfrh = pd.read_excel("./data/raw/Données+RH.xlsx")

In [22]:
dfrh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID salarié             161 non-null    int64
 1   Nom                    161 non-null    object
 2   Prénom                 161 non-null    object
 3   Date de naissance      161 non-null    datetime64[ns]
 4   BU                     161 non-null    object
 5   Date d'embauche        161 non-null    datetime64[ns]
 6   Salaire brut           161 non-null    int64
 7   Type de contrat        161 non-null    object
 8   Nombre de jours de CP  161 non-null    int64
 9   Adresse du domicile    161 non-null    object
 10  Moyen de déplacement   161 non-null    object
dtypes: datetime64[ns](2), int64(3), object(6)
memory usage: 14.0+ KB

In [15]:
dfrh

,ID salarié,Nom,Prénom,Date de naissance,BU,Date d'embauche,Salaire brut,Type de contrat,Nombre de jours de CP,Adresse du domicile,Moyen de déplacement
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running
...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres

In [23]:
dfsport = pd.read_excel("./data/raw/Données+Sportive.xlsx")
dfsport

     ID salarié Pratique d'un sport
0         59019                 NaN
1         19841                 NaN
2         56482              Tennis
3         21886                 NaN
4         81001                 NaN
..          ...                 ...
156       18941              Runing
157       81676              Tennis
158       27069              Runing
159       30256                 NaN
160       94680            Natation

[161 rows x 2 columns]

In [29]:
dfsport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID salarié           161 non-null    int64
 1   Pratique d'un sport  95 non-null     object
dtypes: int64(1), object(1)
memory usage: 2.6+ KB